import { caffieneTheme } from "./themes/caffiene.theme";
import { cosmicNightTheme } from "./themes/cosmic-night.theme";
import { doom64Theme } from "./themes/doom64.theme";
import { gruvboxTheme } from "./themes/gruvbox.theme";
import { lavenderMistTheme } from "./themes/lavender-mist.theme";

export const BUILT_IN_THEMES = [
  gruvboxTheme,
  caffieneTheme,
  cosmicNightTheme,
  lavenderMistTheme,
  doom64Theme,
];

export const customProps = [
  "--background",
  "--foreground",
  "--card",
  "--card-foreground",
  "--popover",
  "--popover-foreground",
  "--primary",
  "--primary-foreground",
  "--secondary",
  "--secondary-foreground",
  "--muted",
  "--muted-foreground",
  "--accent",
  "--accent-foreground",
  "--destructive",
  "--destructive-foreground",
  "--border",
  "--input",
  "--ring",
  "--chart-1",
  "--chart-2",
  "--chart-3",
  "--chart-4",
  "--chart-5",
  "--sidebar",
  "--sidebar-foreground",
  "--sidebar-primary",
  "--sidebar-primary-foreground",
  "--sidebar-accent",
  "--sidebar-accent-foreground",
  "--sidebar-border",
  "--sidebar-ring",
  "--font-sans",
  "--font-serif",
  "--font-mono",
  "--radius",
  "--shadow-2xs",
  "--shadow-xs",
  "--shadow-sm",
  "--shadow",
  "--shadow-md",
  "--shadow-lg",
  "--shadow-xl",
  "--shadow-2xl",
];
